The features are the fact whether or not the customer stays in the bank or leave the bank.
Because a bank wants to have the maximum customers.

Right.

That's how they make money.

The more customers they have, the more they have money in the bank and the more they make money from

the diverse products they offer to their customers.

So, of course, their interest is to keep the maximum customers. And therefore, they made this data set to understand the reasons somehow why customers leave the bank. Mostly once they managed to build a predictive model that can predict if any new customer leaves the bank.
You know, a model that was trained, of course, on this dataset. Well, they will deploy this model on new customers. And for all the customers where the model predicts that the customer leaves the bank, well, they will be prepared and they might do some special offer to the customers so that it will stay in the bank.

importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling (1).csv


In [ ]:
dataset = pd.read_csv('Churn_Modelling (1).csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values


In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


Encoding the categorical data

Label encoding 'Gender' column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One-Hot Encoding the 'Geographical region'

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn .preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder ='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into Training and Test set 

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 22)

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

Building a neural network

In [ ]:
ann = tf.keras.models.Sequential()
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units= 6, activation = 'relu'))
#Adding the output layer
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [ ]:
#Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
#Training the ANN on Training Set
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.8182 - accuracy: 0.3545
Epoch 2/100
250/250 [==============================] - 0s 956us/step - loss: 0.6340 - accuracy: 0.7738
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5837 - accuracy: 0.8022
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5498 - accuracy: 0.8047
Epoch 5/100
250/250 [==============================] - 0s 988us/step - loss: 0.5207 - accuracy: 0.8136
Epoch 6/100
250/250 [==============================] - 0s 960us/step - loss: 0.4963 - accuracy: 0.8207
Epoch 7/100
250/250 [==============================] - 0s 974us/step - loss: 0.4792 - accuracy: 0.8196
Epoch 8/100
250/250 [==============================] - 0s 944us/step - loss: 0.4747 - accuracy: 0.8163
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4569 - accuracy: 0.8239
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.444

Predicting the Test results

In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 0]]


Making the confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1551   53]
 [ 231  165]]


0.858

Out of 100 customers, 85 was predicted correctly to either stay or leave bank